const services = {
  gateways: [
    {
      id: 1,
      name: "Bkash",
      img: "/bkash.png",
      sellRate: 1,
      type: "BDT",
      buyRate: 1,
      reserve: 50000,
    },
    {
      id: 2,
      name: "Bitcoin",
      img: "/bitcoin.png",
      sellRate: 106,
      type: "USD",
      buyRate: 119,
      reserve: 3000,
    },
    {
      id: 3,
      name: "Litecoin",
      img: "/litecoin.png",
      sellRate: 101,
      type: "USD",
      buyRate: 118,
      reserve: 2500,
    },
    {
      id: 4,
      name: "Ethereum",
      img: "/ethereum.png",
      sellRate: 101,
      type: "USD",
      buyRate: 118,
      reserve: 200,
    },
    {
      id: 5,
      name: "TRON(TRX)",
      img: "/tron.png",
      sellRate: 101,
      type: "USD",
      buyRate: 118,
      reserve: 200,
    },
    {
      id: 6,
      name: "DOGECOIN",
      img: "/dogecoin.png",
      sellRate: 90,
      type: "USD",
      buyRate: 115,
      reserve: 555,
    },
    {
      id: 7,
      name: "Rocket",
      img: "/rocket.png",
      sellRate: 1,
      type: "BDT",
      buyRate: 1,
      reserve: 5559,
    },
    {
      id: 8,
      name: "Upay",
      img: "/upay.png",
      sellRate: 1,
      type: "BDT",
      buyRate: 1,
      reserve: 5559,
    },
    {
      id: 9,
      name: "USDT(BEP2)",
      img: "/usdt.png",
      sellRate: 100,
      type: "USD",
      buyRate: 118,
      reserve: 59,
    },
    {
      id: 10,
      name: "Payeer",
      img: "/payeer.png",
      sellRate: 99,
      type: "USD",
      buyRate: 115,
      reserve: 599,
    },
    {
      id: 11,
      name: "Binance USDT(P2P)",
      img: "/binance.png",
      sellRate: 106,
      type: "USD",
      buyRate: 118,
      reserve: 599,
    },
    {
      id: 12,
      name: "BUSD(ERC20)",
      img: "/busd.png",
      sellRate: 106,
      type: "USD",
      buyRate: 118,
      reserve: 599,
    },
    {
      id: 13,
      name: "Bitcoin>Coinbase>",
      img: "/bitcoin-coinbase.png",
      sellRate: 105,
      type: "USD",
      buyRate: 118,
      reserve: 599,
    },
  ],
  reviews: [
    {
      id: 1,
      name: "Abid",
      date: "2/5/22",
      body: "Very very trusted site Alhamdulillah 11miniter vitore payment receive korchi... Best of luck",
    },
    {
      id: 2,
      name: "Kabir Ahmed",
      date: "3/5/22",
      body: "এত তারাতাড়ি পেমেন্ট পেয়ে যাব ভাবতে পারি যাক আশা করি সামনে আরো ভালো পাবো",
    },
    {
      id: 3,
      name: "Rakib Hossen",
      date: "7/5/22",
      body: "Very very trusted site Alhamdulillah 11miniter vitore payment receive korchi... Best of luck",
    },
    {
      id: 4,
      name: "Sabbir Ahmed",
      date: "8/5/22",
      body: "এত তারাতাড়ি পেমেন্ট পেয়ে যাব ভাবতে পারি যাক আশা করি সামনে আরো ভালো পাবো",
    },
    {
      id: 5,
      name: "Nobel Hossen",
      date: "7/5/22",
      body: "Very very trusted site Alhamdulillah 11miniter vitore payment receive korchi... Best of luck",
    },
  ],
  latestExchange: [
    {
      id: 1,
      from: { img: "/bitcoin.png", amount: "60 USD" },
      to: { img: "/bkash.png", amount: "6060 BDT" },
      date: " 12/08/2022 17:06",
    },
    {
      id: 2,
      from: { img: "/bitcoin.png", amount: "60 USD" },
      to: { img: "/bkash.png", amount: "6060 BDT" },
      date: " 12/08/2022 17:06",
    },
    {
      id: 3,
      from: { img: "/bitcoin.png", amount: "60 USD" },
      to: { img: "/bkash.png", amount: "6060 BDT" },
      date: " 12/08/2022 17:06",
    },
    {
      id: 4,
      from: { img: "/bitcoin.png", amount: "60 USD" },
      to: { img: "/bkash.png", amount: "6060 BDT" },
      date: " 12/08/2022 17:06",
    },
    {
      id: 5,
      from: { img: "/bitcoin.png", amount: "60 USD" },
      to: { img: "/bkash.png", amount: "6060 BDT" },
      date: " 12/08/2022 17:06",
    },
  ],
};

export default services;
